version: "3.9"

services:
  app:
    build: .
    container_name: go-app
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdbname
      - DB_DSN=host=db user=postgres password=yourpassword dbname=yourdbname port=5432 sslmode=disable
      - REDIS_ADDR=redis:6379
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  pgdata:
